name = "M1DIS"
uuid = "7c40254d-53b2-4e6c-8b18-b05db208bd5f"
version = "1.2.0"
authors = ["Philipp Eitner <eitner@mpia.de> and contributors"]

[deps]
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MUST = "78ff202f-d08f-4a78-aa4d-c8e96fa3dcb9"
TSO = "65303bd6-8358-47a4-91b9-056454446fac"

[sources]
MUST = {rev = "main", url = "https://github.com/pe1995/MUST.jl"}
TSO = {rev = "main", url = "https://github.com/pe1995/TSO.jl"}

[compat]
DifferentialEquations = "7.0 - 7.15"
FastGaussQuadrature = "1.1.0"
